/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.vbm.Areas");jQuery.sap.require("sap.ui.vbm.library");jQuery.sap.require("sap.ui.vbm.VoAggregation");sap.ui.vbm.VoAggregation.extend("sap.ui.vbm.Areas",{metadata:{library:"sap.ui.vbm",defaultAggregation:"items",aggregations:{"items":{type:"sap.ui.vbm.Area",multiple:true,singularName:"item"}},events:{"click":{},"contextMenu":{},"edgeClick":{},"edgeContextMenu":{},"drop":{}}}});sap.ui.vbm.Areas.M_EVENTS={'click':'click','contextMenu':'contextMenu','edgeClick':'edgeClick','edgeContextMenu':'edgeContextMenu','drop':'drop'};
sap.ui.vbm.Areas.prototype.getTemplateObject=function(){var i=this.getId();return{"type":"{00100000-2012-0004-B001-F311DE491C77}","posarray.bind":i+".P","color.bind":i+".C","colorBorder.bind":i+".CB"};};
sap.ui.vbm.Areas.prototype.getDataObject=function(){var v=this.getItems();var s=[];for(var n=0,l=v.length;n<l;++n){var i=v[n];var e={"P":i.getPosition(),"C":i.getColor(),"CB":i.getColorBorder()};s.push(e);}return{"name":this.getId(),"E":s};};
sap.ui.vbm.Areas.prototype.getTypeObject=function(){return{"A":[{"changeable":"true","name":"P","alias":"P","type":"vector"},{"name":"C","alias":"C","type":"color"},{"name":"CB","alias":"CB","type":"string"}]};};
sap.ui.vbm.Areas.prototype.HandleEvent=function(e){var s=e.Action.name;var f="fire"+s[0].toUpperCase()+s.slice(1);var A;if(A=this.FindInstance(e.Action.instance)){if(A.mEventRegistry[s]){if(s=="click"){A.mClickGeoPos=e.Action.AddActionProperties.AddActionProperty[0]['#'];}if(s=="contextMenu"){A.mClickPos=[e.Action.Params.Param[0]['#'],e.Action.Params.Param[1]['#']];jQuery.sap.require("sap.ui.unified.Menu");if(this.oParent.m_VBIContext.m_Menus)this.oParent.m_VBIContext.m_Menus.deleteMenu("DynContextMenu");var m=new sap.ui.unified.Menu();m.vbi_data={};m.vbi_data.menuRef="CTM";m.vbi_data.VBIName="DynContextMenu";A.fireContextMenu({data:e,menu:m});}else A[f]({data:e});A[f]({data:e});}}this[f]({data:e});};
sap.ui.vbm.Areas.prototype.getActionArray=function(a){var i=this.getId();if(this.mEventRegistry["click"]||this.IsEventRegistered("click"))a.push({"id":i+"1","name":"click","refScene":"MainScene","refVO":i,"refEvent":"Click","AddActionProperty":[{"name":"pos"}]});if(this.mEventRegistry["contextMenu"]||this.IsEventRegistered("contextMenu"))a.push({"id":i+"2","name":"contextMenu","refScene":"MainScene","refVO":i,"refEvent":"ContextMenu"});if(this.mEventRegistry["drop"]||this.IsEventRegistered("drop"))a.push({"id":i+"3","name":"drop","refScene":"MainScene","refVO":i,"refEvent":"Drop"});a=sap.ui.vbm.VoAggregation.prototype.getActionArray.apply(this,arguments);if(this.mEventRegistry["edgeClick"]||this.IsEventRegistered("edgeClick"))a.push({"id":i+"7","name":"edgeClick","refScene":"MainScene","refVO":i,"refEvent":"EdgeClick"});if(this.mEventRegistry["edgeContextMenu"]||this.IsEventRegistered("edgeContextMenu"))a.push({"id":i+"8","name":"edgeContextMenu","refScene":"MainScene","refVO":i,"refEvent":"EdgeContextMenu"});return a;};
sap.ui.vbm.Areas.prototype.openDetailWindow=function(i,p){this.oParent.m_bUseClickPos=true;this.oParent.m_DTOpen=true;this.oParent.m_DTSrc=i;this.oParent.m_DTParams=p;this.oParent.m_bWindowsDirty=true;this.oParent.invalidate(this);};
sap.ui.vbm.Areas.prototype.openContextMenu=function(i,m){this.oParent.openContextMenu("Area",i,m);};
