/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.vbm.Boxes");jQuery.sap.require("sap.ui.vbm.library");jQuery.sap.require("sap.ui.vbm.VoAggregation");sap.ui.vbm.VoAggregation.extend("sap.ui.vbm.Boxes",{metadata:{library:"sap.ui.vbm",defaultAggregation:"items",aggregations:{"items":{type:"sap.ui.vbm.Box",multiple:true,singularName:"item"}},events:{"click":{},"contextMenu":{},"drop":{}}}});sap.ui.vbm.Boxes.M_EVENTS={'click':'click','contextMenu':'contextMenu','drop':'drop'};
sap.ui.vbm.Boxes.prototype.getTemplateObject=function(){var i=this.getId();return{"type":"{00100000-2012-0004-B001-BFED458C3076}","scale.bind":i+".S","pos.bind":i+".P","color.bind":i+".C","colorBorder.bind":i+".CB"};};
sap.ui.vbm.Boxes.prototype.getDataObject=function(){var v=this.getItems();var s=[];for(var n=0,l=v.length;n<l;++n){var i=v[n];var e={"P":i.getPosition(),"S":i.getScale(),"C":i.getColor(),"CB":i.getColorBorder()};s.push(e);}return{"name":this.getId(),"E":s};};
sap.ui.vbm.Boxes.prototype.getTypeObject=function(){return{"A":[{"changeable":"true","name":"P","alias":"P","type":"vector"},{"changeable":"true","name":"S","alias":"S","type":"vector"},{"name":"C","alias":"C","type":"color"},{"name":"CB","alias":"CB","type":"color"}]};};
sap.ui.vbm.Boxes.prototype.HandleEvent=function(e){var s=e.Action.name;var f="fire"+s[0].toUpperCase()+s.slice(1);var B;if(B=this.FindInstance(e.Action.instance)){if(B.mEventRegistry[s]){if(s=="click"){B.mClickGeoPos=e.Action.AddActionProperties.AddActionProperty[0]['#'];}if(s=="contextMenu"){B.mClickPos=[e.Action.Params.Param[0]['#'],e.Action.Params.Param[1]['#']];jQuery.sap.require("sap.ui.unified.Menu");if(this.oParent.m_VBIContext.m_Menus)this.oParent.m_VBIContext.m_Menus.deleteMenu("DynContextMenu");var m=new sap.ui.unified.Menu();m.vbi_data={};m.vbi_data.menuRef="CTM";m.vbi_data.VBIName="DynContextMenu";B.fireContextMenu({data:e,menu:m});}else B[f]({data:e});}}this[f]({data:e});};
sap.ui.vbm.Boxes.prototype.getActionArray=function(a){var i=this.getId();if(this.mEventRegistry["click"]||this.IsEventRegistered("click"))a.push({"id":i+"1","name":"click","refScene":"MainScene","refVO":i,"refEvent":"Click","AddActionProperty":[{"name":"pos"}]});if(this.mEventRegistry["contextMenu"]||this.IsEventRegistered("contextMenu"))a.push({"id":i+"2","name":"contextMenu","refScene":"MainScene","refVO":i,"refEvent":"ContextMenu"});if(this.mEventRegistry["drop"]||this.IsEventRegistered("drop"))a.push({"id":i+"3","name":"drop","refScene":"MainScene","refVO":i,"refEvent":"Drop"});a=sap.ui.vbm.VoAggregation.prototype.getActionArray.apply(this,arguments);return a;};
sap.ui.vbm.Boxes.prototype.openDetailWindow=function(i,p){this.oParent.m_bUseClickPos=true;this.oParent.m_DTOpen=true;this.oParent.m_DTSrc=i;this.oParent.m_DTParams=p;this.oParent.m_bWindowsDirty=true;this.oParent.invalidate(this);};
sap.ui.vbm.Boxes.prototype.openContextMenu=function(i,m){this.oParent.openContextMenu("Box",i,m);};
