/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.vbm.GeoCircles");jQuery.sap.require("sap.ui.vbm.library");jQuery.sap.require("sap.ui.vbm.VoAggregation");sap.ui.vbm.VoAggregation.extend("sap.ui.vbm.GeoCircles",{metadata:{library:"sap.ui.vbm",defaultAggregation:"items",aggregations:{"items":{type:"sap.ui.vbm.GeoCircle",multiple:true,singularName:"item"}},events:{"click":{},"contextMenu":{},"drop":{}}}});sap.ui.vbm.GeoCircles.M_EVENTS={'click':'click','contextMenu':'contextMenu','drop':'drop'};
sap.ui.vbm.GeoCircles.prototype.getTemplateObject=function(){var i=this.getId();return{"type":"{00100000-2013-0004-B001-686F01B57873}","midpoint.bind":i+".P","radius.bind":i+".R","color.bind":i+".C","slices.bind":i+".NS",};};
sap.ui.vbm.GeoCircles.prototype.getDataObject=function(){var v=this.getItems();var s=[];for(var n=0,l=v.length;n<l;++n){var i=v[n];var e={"P":i.getPosition(),"R":i.getRadius(),"C":i.getColor(),"NS":i.getSlices()};s.push(e);}return{"name":this.getId(),"E":s};};
sap.ui.vbm.GeoCircles.prototype.getTypeObject=function(){return{"A":[{"changeable":"true","name":"P","alias":"P","type":"vector"},{"changeable":"true","name":"R","alias":"R","type":"long"},{"name":"C","alias":"C","type":"string"},{"name":"NS","alias":"NS","type":"long"}]};};
sap.ui.vbm.GeoCircles.prototype.HandleEvent=function(e){var s=e.Action.name;var f="fire"+s[0].toUpperCase()+s.slice(1);var G;if(G=this.FindInstance(e.Action.instance)){if(G.mEventRegistry[s]){if(s=="click"){G.mClickGeoPos=e.Action.AddActionProperties.AddActionProperty[0]['#'];}if(s=="contextMenu"){G.mClickPos=[e.Action.Params.Param[0]['#'],e.Action.Params.Param[1]['#']];jQuery.sap.require("sap.ui.unified.Menu");if(this.oParent.m_VBIContext.m_Menus)this.oParent.m_VBIContext.m_Menus.deleteMenu("DynContextMenu");var m=new sap.ui.unified.Menu();m.vbi_data={};m.vbi_data.menuRef="CTM";m.vbi_data.VBIName="DynContextMenu";G.fireContextMenu({data:e,menu:m});}else G[f]({data:e});}}this[f]({data:e});};
sap.ui.vbm.GeoCircles.prototype.openDetailWindow=function(i,p){this.oParent.m_bUseClickPos=true;this.oParent.m_DTOpen=true;this.oParent.m_DTSrc=i;this.oParent.m_DTParams=p;this.oParent.m_bWindowsDirty=true;this.oParent.invalidate(this);};
sap.ui.vbm.GeoCircles.prototype.getActionArray=function(a){var i=this.getId();if(this.mEventRegistry["click"]||this.IsEventRegistered("click"))a.push({"id":i+"1","name":"click","refScene":"MainScene","refVO":i,"refEvent":"Click","AddActionProperty":[{"name":"pos"}]});if(this.mEventRegistry["contextMenu"]||this.IsEventRegistered("contextMenu"))a.push({"id":i+"2","name":"contextMenu","refScene":"MainScene","refVO":i,"refEvent":"ContextMenu"});if(this.mEventRegistry["drop"]||this.IsEventRegistered("drop"))a.push({"id":i+"3","name":"drop","refScene":"MainScene","refVO":i,"refEvent":"Drop"});a=sap.ui.vbm.VoAggregation.prototype.getActionArray.apply(this,arguments);return a;};
sap.ui.vbm.GeoCircles.prototype.openContextMenu=function(i,m){this.oParent.openContextMenu("GeoCircle",i,m);};
