/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.vbm.GeoMap");jQuery.sap.require("sap.ui.vbm.library");jQuery.sap.require("sap.ui.vbm.VBI");sap.ui.vbm.VBI.extend("sap.ui.vbm.GeoMap",{metadata:{library:"sap.ui.vbm",properties:{"mapConfiguration":{type:"object",group:"Misc",defaultValue:null},"legendVisible":{type:"boolean",group:"Misc",defaultValue:true}},defaultAggregation:"vos",aggregations:{"vos":{type:"sap.ui.vbm.VoAggregation",multiple:true,singularName:"vo"},"resources":{type:"sap.ui.vbm.Resource",multiple:true,singularName:"resource"},"legend":{type:"sap.ui.vbm.Legend",multiple:false}},events:{"click":{},"contextMenu":{},"drop":{}}}});sap.ui.vbm.GeoMap.M_EVENTS={'click':'click','contextMenu':'contextMenu','drop':'drop'};sap.ui.vbm.GeoMap.DefaultApplicationURL="media/geomap/geomap.json";
sap.ui.vbm.GeoMap.prototype.exit=function(){sap.ui.vbm.VBI.prototype.exit.apply(this,arguments);this.detachEvent('submit',sap.ui.vbm.GeoMap.prototype.onGeoMapSubmit,this);this.detachEvent('openWindow',sap.ui.vbm.GeoMap.prototype.onGeoMapOpenWindow,this);this.detachEvent('closeWindow',sap.ui.vbm.GeoMap.prototype.onGeoMapCloseWindow,this);};
sap.ui.vbm.GeoMap.prototype.resize=function(e){sap.ui.vbm.VBI.prototype.resize.apply(this,arguments);};
sap.ui.vbm.GeoMap.prototype.onAfterRendering=function(){sap.ui.vbm.VBI.prototype.onAfterRendering.apply(this,arguments);};
sap.ui.vbm.GeoMap.prototype.destroyResources=function(){this.m_bResourcesDirty=true;return this.destroyAggregation("resources");};
sap.ui.vbm.GeoMap.prototype.addResource=function(o){this.m_bResourcesDirty=true;return this.addAggregation("resources",o);};
sap.ui.vbm.GeoMap.prototype.removeResource=function(o){this.m_bResourcesDirty=true;return this.removeAggregation("resources",o);};
sap.ui.vbm.GeoMap.prototype.removeAllResources=function(o){this.m_bResourcesDirty=true;return this.removeAllAggregation("resources");};
sap.ui.vbm.GeoMap.prototype.destroyVos=function(){this.m_bVosDirty=true;return this.destroyAggregation("vos");};
sap.ui.vbm.GeoMap.prototype.addVo=function(o){this.m_bVosDirty=true;return this.addAggregation("vos",o);};
sap.ui.vbm.GeoMap.prototype.removeVo=function(o){this.m_bVosDirty=true;return this.removeAggregation("vos",o);};
sap.ui.vbm.GeoMap.prototype.removeAllVos=function(o){this.m_bVosDirty=true;return this.removeAllAggregation("vos");};
sap.ui.vbm.GeoMap.prototype.setMapConfiguration=function(o){this.m_bMapConfigurationDirty=true;this.setProperty("mapConfiguration",o);};
sap.ui.vbm.GeoMap.prototype.onGeoMapSubmit=function(e){var d=JSON.parse(e.mParameters.data);var c;if(c=this.GetAggregatorContainer(d.Action.object))return c.HandleEvent(d);switch(d.Action.name){case"click":this.fireClick({pos:d.Action.AddActionProperties.AddActionProperty[0]['#']});break;case"contextMenu":this.fireContextMenu({clientX:d.Action.Params.Param[0]['#'],clientY:d.Action.Params.Param[1]['#'],pos:d.Action.AddActionProperties.AddActionProperty[0]['#']});break;case"drop":this.fireDrop({pos:d.Action.AddActionProperties.AddActionProperty[0]['#']});break;};};
sap.ui.vbm.GeoMap.prototype.onGeoMapOpenWindow=function(e){var d=e.getParameter("contentarea");if(d.m_ID){var c;if(c=this.GetAggregatorContainer(d.m_ID))if(c.HandleOpenWindow)c.HandleOpenWindow(e);}};
sap.ui.vbm.GeoMap.prototype.onGeoMapCloseWindow=function(e){var d=e.getParameter("contentarea");if(d.m_ID){var c;if(c=this.GetAggregatorContainer(d.m_ID))if(c.HandleCloseWindow)c.HandleCloseWindow(e);}if(this.m_DTOpen&&e.getParameter("id")=="Detail"){this.m_DTOpen=false;this.m_DTSrc=null;this.m_bWindowsDirty=true;}};
sap.ui.vbm.GeoMap.prototype.init=function(){this.attachEvent('submit',sap.ui.vbm.GeoMap.prototype.onGeoMapSubmit,this);this.attachEvent('openWindow',sap.ui.vbm.GeoMap.prototype.onGeoMapOpenWindow,this);this.attachEvent('closeWindow',sap.ui.vbm.GeoMap.prototype.onGeoMapCloseWindow,this);this.m_bVosDirty=true;this.m_bMapConfigurationDirty=true;this.m_bResourcesDirty=true;this.m_bMapProvidersDirty=true;this.m_bMapLayerStacksDirty=true;this.m_bWindowsDirty=true;this.m_bMapconfigDirty=true;this.m_bLegendDirty=true;sap.ui.vbm.VBI.prototype.init.apply(this,arguments);};
sap.ui.vbm.GeoMap.prototype.getWindowsObject=function(){var w={"Set":[{"name":"Main","Window":{"id":"Main","caption":"MainWindow","type":"geo","refParent":"","refScene":"MainScene","modal":"true"}}]};var l=this.getLegend();if(l){var L=l.getTemplateObject();if(L.Set)w.Set=w.Set.concat(L.Set);if(L.Remove){if(!w.Remove)w.Remove=L.Remove;else w.Set=w.Set.concat(L.Remove);}}if(this.m_DTSrc&&this.m_DTOpen){var d;if(this.m_bUseClickPos==true&&this.m_DTSrc.mClickGeoPos)d={"Set":[{"name":"Detail","Window":{"id":"Detail","type":"callout","refParent":"Main","refScene":"","modal":"true","caption":this.m_DTParams.caption?this.m_DTParams.caption:"","offsetX":this.m_DTParams.offsetX?this.m_DTParams.offsetX:"0","offsetY":this.m_DTParams.offsetY?this.m_DTParams.offsetY:"0","pos":this.m_DTSrc.mClickGeoPos}}]};else d={"Set":[{"name":"Detail","Window":{"id":"Detail","type":"callout","refParent":"Main","refScene":"","modal":"true","caption":this.m_DTParams.caption?this.m_DTParams.caption:"","offsetX":this.m_DTParams.offsetX?this.m_DTParams.offsetX:"0","offsetY":this.m_DTParams.offsetY?this.m_DTParams.offsetY:"0","pos.bind":this.m_DTSrc.oParent.sId+"."+this.m_DTSrc.sId+".P"}}]};w.Set=w.Set.concat(d.Set);var D={"Remove":[{"name":"Detail"}]};if(!w.Remove)w.Remove=D.Remove;else w.Set=w.Set.concat(D.Remove);}return w;};
sap.ui.vbm.GeoMap.prototype.getTemplateObject=function(v){var t=v.getTemplateObject(),i=v.getId();t['id']=i;t['datasource']=i;t['hotScale.bind']=t.id+".HS";t['hotDeltaColor.bind']=t.id+".HDC";t['selectColor.bind']=t.id+".SC";t['fxsize.bind']=t.id+".FS";t['fxdir.bind']=t.id+".FD";t['entity.bind']=t.id+".ET";t['labelText.bind']=t.id+".LT";t['labelBgColor.bind']=t.id+".LBC";t['labelPos.bind']=t.id+".LP";t['tooltip.bind']=t.id+".TT";return t;};
sap.ui.vbm.GeoMap.prototype.getDataObject=function(v,n){var t=v.getDataObject();t['name']=v.getId();if(n)return t;var s=t.E;var V=v.getItems();for(var a=0,l=V.length;a<l;++a){var b,i=s[a],o=V[a];i['K']=o.getId();i['VB:c']=o.getChangable();i['HS']=o.getHotScale();i['HDC']=o.getHotDeltaColor();i['SC']=o.getSelectColor();i['FS']=o.getFxsize();i['FD']=o.getFxdir();i['ET']=o.getEntity();i['LT']=o.getLabelText();i['LBC']=o.getLabelBgColor();i['LP']=o.getLabelPos();i['TT']=(b=o.getTooltip())?b:"";}return t;};
sap.ui.vbm.GeoMap.prototype.getTypeObject=function(v,n){var t=v.getTypeObject();var i=v.getId();t['name']=i;if(n)return t;t['key']='K';var a=t.A;t.A=a.concat([{"name":"K","alias":"K","type":"string"},{"name":"HS","alias":"HS","type":"vector"},{"name":"HDC","alias":"HDC","type":"string"},{"name":"SC","alias":"SC","type":"string"},{"name":"FS","alias":"FS","type":"boolean"},{"name":"ET","alias":"ET","type":"string"},{"name":"LT","alias":"LT","type":"string"},{"name":"LBC","alias":"LBC","type":"color"},{"name":"LP","alias":"LP","type":"long"},{"name":"TT","alias":"TT","type":"string"}]);return t;};
sap.ui.vbm.GeoMap.prototype.getActionArray=function(v,s){var t=(s)?s:[];if(v){t=v.getActionArray(s);}else{var i=this.getId();if(this.mEventRegistry["click"])t.push({"id":i+"1","name":"click","refScene":"MainScene","refVO":"Map","refEvent":"Click","AddActionProperty":[{"name":"pos"}]});if(this.mEventRegistry["contextMenu"])t.push({"id":i+"2","name":"contextMenu","refScene":"MainScene","refVO":"Map","refEvent":"ContextMenu","AddActionProperty":[{"name":"pos"}]});if(this.mEventRegistry["drop"])t.push({"id":i+"3","name":"drop","refScene":"MainScene","refVO":"Map","refEvent":"Drop","AddActionProperty":[{"name":"pos"}]});if(this.mEventRegistry["submit"])t.push({"id":i+"4","name":"zoomChanged","refScene":"MainScene","refVO":"Map","refEvent":"ZoomChanged","AddActionProperty":[{"name":"zoom"},{"name":"centerpoint"},{"name":"pos"}]});if(this.mEventRegistry["submit"])t.push({"id":i+"5","name":"centerChanged","refScene":"MainScene","refVO":"Map","refEvent":"CenterChanged","AddActionProperty":[{"name":"zoom"},{"name":"centerpoint"},{"name":"pos"}]});}return t;};
sap.ui.vbm.GeoMap.prototype.MinimizeApp=function(a){var t,s;s=null;if(!this.m_bWindowsDirty)(t=a)&&(t=t.SAPVB)&&(t=t.Windows)&&(s=JSON.stringify(t))&&(s==this.m_curWindows)&&(delete a.SAPVB.Windows)||(this.m_curWindows=s?s:this.m_curWindows);else this.m_bWindowsDirty=false;s=null;(t=a)&&(t=t.SAPVB)&&(t=t.Scenes)&&(s=JSON.stringify(t))&&(s==this.m_curScenes)&&(delete a.SAPVB.Scenes)||(this.m_curScenes=s?s:this.m_curScenes);s=null;(t=a)&&(t=t.SAPVB)&&(t=t.Actions)&&(s=JSON.stringify(t))&&(s==this.m_curActions)&&(delete a.SAPVB.Actions)||(this.m_curActions=s?s:this.m_curActions);s=null;(t=a)&&(t=t.SAPVB)&&(t=t.DataTypes)&&(s=JSON.stringify(t))&&(s==this.m_curDataTypes)&&(delete a.SAPVB.DataTypes)||(this.m_curDataTypes=s?s:this.m_curDataTypes);s=null;(t=a)&&(t=t.SAPVB)&&(t=t.Data)&&(s=JSON.stringify(t))&&(s==this.m_curData)&&(delete a.SAPVB.Data)||(this.m_curData=s?s:this.m_curData);return a;};
sap.ui.vbm.GeoMap.prototype.GetAggregatorContainer=function(i){var v=this.getVos();if(!v||!v.length)return;for(var n=0,l=v.length;n<l;++n){if(v[n].sId==i)return v[n];}return null;};
sap.ui.vbm.GeoMap.prototype.Update=function(){var a=this.UpdateGeoMapData();return this.MinimizeApp(a);};
sap.ui.vbm.GeoMap.prototype.UpdateGeoMapData=function(){var p=sap.ui.vbm.GeoMap.ApplicationURL?sap.ui.vbm.GeoMap.ApplicationURL:sap.ui.resource("sap.ui.vbm",sap.ui.vbm.GeoMap.DefaultApplicationURL);var j=jQuery.sap.syncGetJSON(p);var a=j.data;if(this.m_bResourcesDirty)this.UpdateResourceData(a);this.UpdateVOData(a);if(this.m_bMapConfigurationDirty)this.UpdateMapConfiguration(a);this.UpdateMapProviders(a);this.UpdateMapLayerStacks(a);this.UpdateWindows(a);if(a.SAPVB.Actions)this.getActionArray(null,a.SAPVB.Actions.Set.Action);return a;};
sap.ui.vbm.GeoMap.prototype.UpdateMapProviders=function(a){if(!this.m_bMapProvidersDirty)delete a.SAPVB.MapProviders;this.m_bMapProvidersDirty=false;};
sap.ui.vbm.GeoMap.prototype.UpdateMapLayerStacks=function(a){if(!this.m_bMapLayerStacksDirty)delete a.SAPVB.MapLayerStacks;this.m_bMapLayerStacksDirty=false;};
sap.ui.vbm.GeoMap.prototype.UpdateWindows=function(a){a.SAPVB.Windows=this.getWindowsObject();};
sap.ui.vbm.GeoMap.prototype.UpdateMapConfiguration=function(a){if(!this.m_bMapConfigurationDirty)return;this.m_bMapConfigurationDirty=false;var c=this.getMapConfiguration();if(c){a.SAPVB.MapProviders={Set:{MapProvider:c.MapProvider}};a.SAPVB.MapLayerStacks={Set:{MapLayerStack:c.MapLayerStacks}};}return;};
sap.ui.vbm.GeoMap.prototype.UpdateResourceData=function(a){if(!this.m_bResourcesDirty)return;this.m_bResourcesDirty=false;var r=this.getResources();((a.SAPVB.Resources={}).Set={}).Resource=[];function R(){var a=this.Update();this.load(a);};for(var n=0,l=r.length;n<l;++n){var b=r[n];if(!b.mProperties.value&&b.mProperties.src){var c=document.createElement('myCanvas');var i=document.createElement('img');b.m_Img=i;var f=function(b){var c=document.createElement('canvas');c.width=b.m_Img.width;c.height=b.m_Img.height;var d=c.getContext('2d');d.drawImage(b.m_Img,0,0);b.mProperties.value=c.toDataURL();delete b.m_Img;this.m_bResourcesDirty=true;window.setTimeout(R.bind(this),10);};i.onload=f.bind(this,b);i.src=b.mProperties.src;}else a.SAPVB.Resources.Set.Resource.push({"name":(b.mProperties.name?b.mProperties.name:b.sId),"value":b.mProperties.value});}return;};
sap.ui.vbm.GeoMap.prototype.UpdateVOData=function(a){this.m_bVosDirty=false;var v=this.getVos();var s=[];var b=[];var c=[];var d=[];for(var n=0,l=v.length;n<l;++n){var C=v[n];s.push(this.getTemplateObject(C));b.push(this.getDataObject(C));c.push(this.getTypeObject(C));d=this.getActionArray(C,d);}var L=this.getLegend();if(L){b.push(this.getDataObject(L,true));c.push(this.getTypeObject(L,true));}var m=(!this.m_saVO||!(JSON.stringify(this.m_saVO)===JSON.stringify(s)))?true:false;this.m_saVO=s;((a.SAPVB.Data={}).Set={}).N=b;m&&(((a.SAPVB.DataTypes={}).Set={}).N=c);m&&(((a.SAPVB.Actions={}).Set={}).Action=d);m&&((((a.SAPVB.Scenes={}).Set={}).SceneGeo={"id":"MainScene","refMapLayerStack":"Default","initialZoom":"2",}).VO=s);};
sap.ui.vbm.GeoMap.prototype.invalidate=function(s){if(s instanceof sap.ui.vbm.Areas||s instanceof sap.ui.vbm.Boxes||s instanceof sap.ui.vbm.Circles||s instanceof sap.ui.vbm.Containers||s instanceof sap.ui.vbm.GeoCircles||s instanceof sap.ui.vbm.Pies||s instanceof sap.ui.vbm.Routes||s instanceof sap.ui.vbm.Spots){this.m_bLegendDirty=true;this.m_bVosDirty=true;}if(s instanceof sap.ui.vbm.Legend){this.m_bLegendDirty=true;this.m_bVosDirty=true;}sap.ui.core.Control.prototype.invalidate.apply(this,arguments);};
sap.ui.vbm.GeoMap.prototype.openContextMenu=function(t,i,m){if(m&&m.vbi_data&&m.vbi_data.VBIName=="DynContextMenu"){if(!this.m_VBIContext.m_Menus)this.m_VBIContext.m_Menus=new window.VBI.Menus();this.m_VBIContext.m_Menus.m_menus.push(m);var a={"SAPVB":{"version":"2.0","Automation":{"Call":{"earliest":"0","handler":"CONTEXTMENUHANDLER","instance":i.sId,"name":"SHOW","object":t,"refID":"CTM","Param":[{"name":"x","#":i.mClickPos[0]},{"name":"y","#":i.mClickPos[1]},{"name":"scene","#":"MainScene"}]}}}};this.loadHtml(a);}};
