/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.vbm.Pies");jQuery.sap.require("sap.ui.vbm.library");jQuery.sap.require("sap.ui.vbm.VoAggregation");sap.ui.vbm.VoAggregation.extend("sap.ui.vbm.Pies",{metadata:{library:"sap.ui.vbm",defaultAggregation:"items",aggregations:{"items":{type:"sap.ui.vbm.Pie",multiple:true,singularName:"item"}},events:{"click":{},"contextMenu":{},"drop":{}}}});sap.ui.vbm.Pies.M_EVENTS={'click':'click','contextMenu':'contextMenu','drop':'drop'};
sap.ui.vbm.Pies.prototype.getTemplateObject=function(){var i=this.getId();return{"type":"{00100000-2012-0004-B001-383477EA1DEB}","pos.bind":i+".P","tooltip.bind":i+".TT","scale.bind":i+".S","series.bind":i+".Series","text.bind":i+".Series.T","value.bind":i+".Series.V"};};
sap.ui.vbm.Pies.prototype.getDataObject=function(){var v=this.getItems();var s=[];for(var n=0,l=v.length;n<l;++n){var i=v[n];var S=[];var p=i.getItems();for(var a=0,b=p.length;a<b;++a){var I=p[a];var e={"T":I.getName(),"V":I.getValue()};S.push(e);}var E={"P":i.getPosition(),"TT":i.getTooltip(),"S":i.getScale(),"N":{"name":"Series","E":S}};s.push(E);}return{"name":this.getId(),"E":s};};
sap.ui.vbm.Pies.prototype.getTypeObject=function(){return{"A":[{"changeable":"true","name":"P","alias":"P","type":"vector"},{"name":"TT","alias":"TT","type":"string"},{"changeable":"true","name":"S","alias":"S","type":"string"}],"N":{"name":"Series","A":[{"name":"V","alias":"V","type":"float"},{"name":"T","alias":"T","type":"string"}]}};};
sap.ui.vbm.Pies.prototype.HandleEvent=function(e){var s=e.Action.name;var f="fire"+s[0].toUpperCase()+s.slice(1);var P;if(P=this.FindInstance(e.Action.instance)){if(P.mEventRegistry[s]){if(s=="contextMenu"){P.mClickPos=[e.Action.Params.Param[0]['#'],e.Action.Params.Param[1]['#']];jQuery.sap.require("sap.ui.unified.Menu");if(this.oParent.m_VBIContext.m_Menus)this.oParent.m_VBIContext.m_Menus.deleteMenu("DynContextMenu");var m=new sap.ui.unified.Menu();m.vbi_data={};m.vbi_data.menuRef="CTM";m.vbi_data.VBIName="DynContextMenu";P.fireContextMenu({data:e,menu:m});}else P[f]({data:e});}}this[f]({data:e});};
sap.ui.vbm.Pies.prototype.openDetailWindow=function(i,p){this.oParent.m_bUseClickPos=false;this.oParent.m_DTOpen=true;this.oParent.m_DTSrc=i;this.oParent.m_DTParams=p;this.oParent.m_bWindowsDirty=true;this.oParent.invalidate(this);};
sap.ui.vbm.Pies.prototype.getActionArray=function(a){var i=this.getId();if(this.mEventRegistry["click"]||this.IsEventRegistered("click"))a.push({"id":i+"1","name":"click","refScene":"MainScene","refVO":i,"refEvent":"Click","AddActionProperty":[{"name":"pos"}]});if(this.mEventRegistry["contextMenu"]||this.IsEventRegistered("contextMenu"))a.push({"id":i+"2","name":"contextMenu","refScene":"MainScene","refVO":i,"refEvent":"ContextMenu"});if(this.mEventRegistry["drop"]||this.IsEventRegistered("drop"))a.push({"id":i+"3","name":"drop","refScene":"MainScene","refVO":i,"refEvent":"Drop"});a=sap.ui.vbm.VoAggregation.prototype.getActionArray.apply(this,arguments);return a;};
sap.ui.vbm.Pies.prototype.openContextMenu=function(i,m){this.oParent.openContextMenu("Pie",i,m);};
