/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.vbm.Spots");jQuery.sap.require("sap.ui.vbm.library");jQuery.sap.require("sap.ui.vbm.VoAggregation");sap.ui.vbm.VoAggregation.extend("sap.ui.vbm.Spots",{metadata:{library:"sap.ui.vbm",defaultAggregation:"items",aggregations:{"items":{type:"sap.ui.vbm.Spot",multiple:true,singularName:"item"},"dragSource":{type:"sap.ui.vbm.DragSource",multiple:true,singularName:"dragSource"},"dropTarget":{type:"sap.ui.vbm.DropTarget",multiple:true,singularName:"dropTarget"}},events:{"click":{},"contextMenu":{},"drop":{}}}});sap.ui.vbm.Spots.M_EVENTS={'click':'click','contextMenu':'contextMenu','drop':'drop'};
sap.ui.vbm.Spots.prototype.getTemplateObject=function(){var i=this.getId();var d=this.getDragSource();var D=[];for(var n=0,l=d.length;n<l;++n){var o=d[n];var e={"type":o.getType()};D.push(e);}D.push({"datasource":i+".DS","type.bind":i+".DS.DGT",});var a=this.getDropTarget();var s=[];for(var n=0,l=a.length;n<l;++n){var b=a[n];var e={"type":b.getType()};s.push(e);}s.push({"datasource":i+".DT","type.bind":i+".DT.DPT"});return{"type":"{00100000-2012-0004-B001-64592B8DB964}","scale.bind":i+".S","image.bind":i+".I","pos.bind":i+".P","text.bind":i+".T","alignment.bind":i+".AL","dragdata.bind":i+".DD","DragSource":{"DragItem":D},"DropTarget":{"DropItem":s}};};
sap.ui.vbm.Spots.prototype.getDataObject=function(){var v=this.getItems();var s=[];var d=[];var e,D,o;for(var n=0,l=v.length;n<l;++n){var i=v[n];d=[];var a=[];var b=0;var c=i.getDragSource();for(var f=0,g=c.length;f<g;++f){var I=c[f];var E={"VB:ix":b++,"A":I.getType()};a.push(E);}if(a.length>0){D={"name":"DS","E":a};d.push(D);}var h=[];var j=0;var k=i.getDropTarget();for(var f=0,m=k.length;f<m;++f){var p=k[f];var q={"VB:ix":j++,"A":p.getType()};h.push(q);}if(h.length>0){o={"name":"DT","E":h};d.push(o);}e={"P":i.getPosition(),"S":i.getScale(),"T":i.getText(),"I":i.getImage(),"AL":i.getAlignment(),"DD":i.getDragData(),"N":d};s.push(e);}return{"name":this.getId(),"E":s};};
sap.ui.vbm.Spots.prototype.getTypeObject=function(){return{"A":[{"changeable":"true","name":"P","alias":"P","type":"vector"},{"changeable":"true","name":"S","alias":"S","type":"vector"},{"name":"T","alias":"T","type":"string"},{"name":"I","alias":"I","type":"string"},{"name":"AL","alias":"AL","type":"string"},{"name":"DD","alias":"DD","type":"string"}],"N":[{"name":"DS","A":{"name":"DGT","alias":"A","type":"string"}},{"name":"DT","A":{"name":"DPT","alias":"A","type":"string"}}]};};
sap.ui.vbm.Spots.prototype.HandleEvent=function(e){var s=e.Action.name;var f="fire"+s[0].toUpperCase()+s.slice(1);var a;if(a=this.FindInstance(e.Action.instance)){if(a.mEventRegistry[s]){if(s=="contextMenu"){a.mClickPos=[e.Action.Params.Param[0]['#'],e.Action.Params.Param[1]['#']];jQuery.sap.require("sap.ui.unified.Menu");if(this.oParent.m_VBIContext.m_Menus)this.oParent.m_VBIContext.m_Menus.deleteMenu("DynContextMenu");var m=new sap.ui.unified.Menu();m.vbi_data={};m.vbi_data.menuRef="CTM";m.vbi_data.VBIName="DynContextMenu";a.fireContextMenu({data:e,menu:m});}else a[f]({data:e});}}this[f]({data:e});};
sap.ui.vbm.Spots.prototype.openDetailWindow=function(i,p){this.oParent.m_bUseClickPos=false;this.oParent.m_DTOpen=true;this.oParent.m_DTSrc=i;this.oParent.m_DTParams=p;this.oParent.m_bWindowsDirty=true;this.oParent.invalidate(this);};
sap.ui.vbm.Spots.prototype.openContextMenu=function(i,m){this.oParent.openContextMenu("Spot",i,m);};
sap.ui.vbm.Spots.prototype.getActionArray=function(a){var i=this.getId();if(this.mEventRegistry["click"]||this.IsEventRegistered("click"))a.push({"id":i+"1","name":"click","refScene":"MainScene","refVO":i,"refEvent":"Click","AddActionProperty":[{"name":"pos"}]});if(this.mEventRegistry["contextMenu"]||this.IsEventRegistered("contextMenu"))a.push({"id":i+"2","name":"contextMenu","refScene":"MainScene","refVO":i,"refEvent":"ContextMenu"});if(this.mEventRegistry["drop"]||this.IsEventRegistered("drop"))a.push({"id":i+"3","name":"drop","refScene":"MainScene","refVO":i,"refEvent":"Drop"});a=sap.ui.vbm.VoAggregation.prototype.getActionArray.apply(this,arguments);return a;};
