/*!
 * SAP UI development toolkit for HTML5 (SAPUI5) (c) Copyright 2009-2012 SAP AG. All rights reserved
 */
jQuery.sap.declare("sap.ui.vbm.VBI");jQuery.sap.require("sap.ui.vbm.library");jQuery.sap.require("sap.ui.core.Control");sap.ui.core.Control.extend("sap.ui.vbm.VBI",{metadata:{publicMethods:["load","zoomToGeoPosition"],library:"sap.ui.vbm",properties:{"width":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:'800px'},"height":{type:"sap.ui.core.CSSSize",group:"Misc",defaultValue:'600px'},"config":{type:"object",group:"Misc",defaultValue:null},"plugin":{type:"boolean",group:"Misc",defaultValue:false}},events:{"submit":{},"render":{},"zoom":{},"move":{},"openWindow":{},"closeWindow":{}}}});sap.ui.vbm.VBI.M_EVENTS={'submit':'submit','render':'render','zoom':'zoom','move':'move','openWindow':'openWindow','closeWindow':'closeWindow'};jQuery.sap.require("sap.ui.vbm.lib.sapvbi");jQuery.sap.require("sap.ui.thirdparty.jqueryui.jquery-ui-core");jQuery.sap.require("sap.ui.thirdparty.jqueryui.jquery-ui-widget");jQuery.sap.require("sap.ui.thirdparty.jqueryui.jquery-ui-mouse");jQuery.sap.require("sap.ui.thirdparty.jqueryui.jquery-ui-draggable");jQuery.sap.require("sap.ui.core.IconPool");
sap.ui.vbm.VBI.prototype.exit=function(){if(this.getPlugin()){var p=this.GetPlugInControl();if(p)p.OnSubmit=null;}else{if(this.m_VBIContext)this.m_VBIContext.clear();}if(this.resizeID!=""){sap.ui.core.ResizeHandler.deregister(this.resizeID);this.resizeID="";}};
sap.ui.vbm.VBI.prototype.resize=function(e){var c=(this.oControl!=undefined)?this.oControl:this;var a=c.m_VBIContext;if(a){var s=a.GetMainScene();if(s)s.resizeCanvas(e);}};
sap.ui.vbm.VBI.prototype.init=function(){this.m_aLoadQueue=null;if(this.getPlugin()){}else{this.m_VBIContext=new VBI.VBIContext(this);}this.resizeID="";};
sap.ui.vbm.VBI.prototype.loadNative=function(d){var l=this.getId();var a=document.getElementById('VBI'+l);if(!a)return;var s=function(b){try{var D;if(D=JSON.parse(b)){var v=D.SAPVB;var t=JSON.stringify(v,null,'  ');this.fireSubmit({data:t});}}catch(e){VBI.m_bTrace&&VBI.Trace("Error submitting plugin event");}};if(jQuery.type(d)=='object'){var t=JSON.stringify(d,null,'  ');try{a.Load(t);a.OnSubmit=s.bind(this);}catch(e){}}else if(jQuery.type(d)=='string'){try{a.Load(d);a.OnSubmit=s.bind(this);}catch(e){}}};
sap.ui.vbm.VBI.prototype.loadHtml=function(d){var l=this.getId();var a=null;if(typeof d=='string')a=JSON.parse(d.indexOf('{')?d.substr(d.indexOf('{')):d);else if(typeof d=='object')a=d;if(!a)return;if(!a["SAPVB"]){var m;if(this.m_VBIContext&&(m=(new VBI.Adaptor(this.m_VBIContext)).CreateLoadData(a)))return this.loadHtml(m);else return;}var M=false;var b=false;var c=false;var e=false;var f=false;var g=false;var h=false;var i=false;var j=false;var k=false;var n=false;if(jQuery.type(a)=='object'){if(a.SAPVB){if(a.SAPVB.Config){this.m_VBIContext.GetConfig().load(a.SAPVB.Config,this.m_VBIContext);}if(a.SAPVB.Resources){this.m_VBIContext.GetResources().load(a.SAPVB.Resources,this.m_VBIContext);i=true;}if(a.SAPVB.DataTypes){if(!this.m_VBIContext.m_DataTypeProvider)this.m_VBIContext.m_DataTypeProvider=new VBI.DataTypeProvider();this.m_VBIContext.m_DataTypeProvider.load(a.SAPVB.DataTypes,this.m_VBIContext);M=true;}if(a.SAPVB.Data){if(!this.m_VBIContext.m_DataProvider)this.m_VBIContext.m_DataProvider=new VBI.DataProvider();this.m_VBIContext.m_DataProvider.load(a.SAPVB.Data,this.m_VBIContext);b=true;}if(a.SAPVB.MapProviders){if(!this.m_VBIContext.m_MapProviders)this.m_VBIContext.m_MapProviders=new VBI.MapProviders();this.m_VBIContext.m_MapProviders.load(a.SAPVB.MapProviders,this.m_VBIContext);c=true;}if(a.SAPVB.MapLayerStacks){if(!this.m_VBIContext.m_MapLayerStackManager)this.m_VBIContext.m_MapLayerStackManager=new VBI.MapLayerStackManager(this.m_VBIContext);this.m_VBIContext.m_MapLayerStackManager.load(a.SAPVB.MapLayerStacks,this.m_VBIContext);e=true;}if(a.SAPVB.Windows){if(!this.m_VBIContext.m_Windows)this.m_VBIContext.m_Windows=new VBI.Windows();this.m_VBIContext.m_Windows.load(a.SAPVB.Windows,this.m_VBIContext);g=true;}if(a.SAPVB.Actions){if(!this.m_VBIContext.m_Actions)this.m_VBIContext.m_Actions=new VBI.Actions();this.m_VBIContext.m_Actions.load(a.SAPVB.Actions,this.m_VBIContext);h=true;}if(a.SAPVB.Automation){if(!this.m_VBIContext.m_Automations)this.m_VBIContext.m_Automations=new VBI.Automations();this.m_VBIContext.m_Automations.load(a.SAPVB.Automation,this.m_VBIContext);j=true;}if(a.SAPVB.Menus){if(!this.m_VBIContext.m_Menus)this.m_VBIContext.m_Menus=new VBI.Menus();this.m_VBIContext.m_Menus.load(a.SAPVB.Menus,this.m_VBIContext);k=true;}if(a.SAPVB.Clustering){if(!this.m_VBIContext.m_Clustering)this.m_VBIContext.m_Clustering=new VBI.Clustering();this.m_VBIContext.m_Clustering.load(a.SAPVB.Clustering,this.m_VBIContext);n=true;}if(a.SAPVB.Scenes){if(!this.m_VBIContext.m_SceneManager)this.m_VBIContext.m_SceneManager=new VBI.SceneManager();this.m_VBIContext.m_SceneManager.load(a.SAPVB.Scenes,this.m_VBIContext);f=true;}}if(b)if(this.m_VBIContext.m_Windows)this.m_VBIContext.m_Windows.NotifyDataChange();if(f||g){if(this.m_VBIContext.m_Windows)this.m_VBIContext.m_Windows.Awake(l);}if(f||b||n)if(this.m_VBIContext.m_Windows)this.m_VBIContext.m_Windows.RenderAsync();}};
sap.ui.vbm.VBI.prototype.load=function(d){if(!this.IsRendered()){if(!this.m_aLoadQueue)this.m_aLoadQueue=[];this.m_aLoadQueue.push(d);return;}if(this.getPlugin())return this.loadNative(d);else return this.loadHtml(d);};
sap.ui.vbm.VBI.prototype.zoomToGeoPosition=function(l,a,b){var s=null;if(s=this.m_VBIContext.GetMainScene()){if(jQuery.type(l)=='array'&&jQuery.type(a)=='array'){if(l.length>1&&a.length>1)s.ZoomToMultiplePositions(l,a);else s.ZoomToGeoPosition(VBI.MathLib.DegToRad([parseFloat(l[0]),parseFloat(a[0])]),parseFloat(b));}else s.ZoomToGeoPosition(VBI.MathLib.DegToRad([parseFloat(l),parseFloat(a)]),parseFloat(b));}};
sap.ui.vbm.VBI.prototype.zoomToAreas=function(a,c){var s=null;if(s=this.m_VBIContext.GetMainScene()){s.ZoomToAreas(a,c);}};
sap.ui.vbm.VBI.prototype.onAfterRendering=function(){if(this.$oldContent.length>0){this.$().append(this.$oldContent);}if(this.m_aLoadQueue){var n;for(n=0;n<this.m_aLoadQueue.length;++n)this.load(this.m_aLoadQueue[n]);this.m_aLoadQueue=null;}if(this.resizeID==""){this.resize();this.resizeID=sap.ui.core.ResizeHandler.register(this,this.resize);}var l=this.getId();if(this.m_VBIContext.m_Windows)this.m_VBIContext.m_Windows.Awake(l);};
sap.ui.vbm.VBI.prototype.onBeforeRendering=function(){this.$oldContent=sap.ui.core.RenderManager.findPreservedContent(this.getId());};
sap.ui.vbm.VBI.prototype.IsRendered=function(){return this.getDomRef()?true:false;};
sap.ui.vbm.VBI.prototype.GetPlugInControl=function(){var l=this.getId();var e=document.getElementById('VBI'+l);return e?e:null;};
sap.ui.vbm.VBI.prototype.setConfig=function(c){return this.load(c);};
sap.ui.vbm.VBI.prototype.setWidth=function(v){if(typeof v==='number')this.setProperty("width",parseInt(v,10).toString()+"px");else this.setProperty("width",v);};
sap.ui.vbm.VBI.prototype.setHeight=function(v){if(typeof v==='number')this.setProperty("height",parseInt(v,10).toString()+"px");else this.setProperty("height",v);};
